# Generated by Django 5.1.3 on 2024-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechReformApp', '0002_remove_motherboard_audio_ports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casing',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hdd',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headphone',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('Cooler', 'Cooler'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('GPU', 'GPU'), ('Power Supply', 'Power Supply'), ('Casing', 'Casing'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone')], help_text='Category of the product', max_length=50, null=True),
        ),
    ]
