# Generated by Django 5.1.3 on 2024-12-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechReformApp', '0003_casing_category_cooler_category_cpu_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='core',
        ),
    ]
